### PR TITLE
CI: use the trust template

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8b8b822 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8b8b822 with merge 8b8b822...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/190023283)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d153f4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d153f4 with merge 9d153f4...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/190028055)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 20c3882 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 20c3882 with merge 20c3882...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/190029650)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c562d5d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c562d5d with merge c562d5d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/190030842)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit acbfb5f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit acbfb5f with merge acbfb5f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/190059956)
Approved by: japaric
Pushing acbfb5fd00d59037007f37db33763dc02740eef6 to master...

**Pull request merged**
