### PR TITLE
quote the output of `git status -s`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 665a6a8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 665a6a8 with merge 665a6a8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/175791599)
Approved by: japaric
Pushing 665a6a8fb496b626f4618e2b2a56b30ee7412736 to master...

**Pull request merged**
