### PR TITLE
add TIM3 and TIM4

### PR DESCRIPTION
**Pull request by astraw**
Hi, Can you merge this? I can verify that TIM3 is working for me and I double checked the memory map for TIM4. Then it would be great to get a new package release on crates.io. Thanks.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @astraw!

> Then it would be great to get a new package release on crates.io.

Will do after this lands.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6f345d1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6f345d1 with merge 6f345d1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/198319653)
Approved by: japaric
Pushing 6f345d1bd7ae997906693f5c77e8f95a0c676af1 to master...

**Comment by japaric** [comment]
released [v0.1.2](https://crates.io/crates/stm32f30x-memory-map/0.1.2).

**Comment by astraw** [comment]
Many thanks, that's great!

**Pull request merged**
