### PR TITLE
add unsafe API to directly modify the bits of registers

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d537b8e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d537b8e with merge d537b8e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/187921713)
Approved by: japaric
Pushing d537b8ed587d02c3565855fe63134178552a588c to master...

**Pull request merged**
