### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 276a85b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 276a85b with merge 276a85b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/175770065)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8b4b5b6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8b4b5b6 with merge 8b4b5b6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/175779759)
Approved by: japaric
Pushing 8b4b5b6bdec3a66e256d8f8067ccc7335eb1cde4 to master...

**Pull request merged**
