### PR TITLE
tweak CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7efe470 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7efe470 with merge 7efe470...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/185796702)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 25bf0d7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 25bf0d7 with merge 25bf0d7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/185801515)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 56b1f55 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 56b1f55 with merge 56b1f55...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/185807553)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bb04da3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bb04da3 with merge bb04da3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-memory-map/builds/185809887)
Approved by: japaric
Pushing bb04da347e19246592ce6d2acacfc455343af0a1 to master...

**Pull request merged**
